stages:
  ingest:
    wdir: .
    cmd: python pipelines/ingest_pipeline.py
    deps:
      - pipelines/ingest_pipeline.py
      - steps/ingest_data.py
      - src/ingest_strategy.py
      - data/raw/ml-100k/u.data
      - data/raw/ml-100k/u.item
      - data/raw/ml-100k/u.user
    params:
      - ingest.base_path
      - ingest.processed_dir
    outs:
      - data/processed
