stages:
  fetch_tmdb_metadata:
    cmd: python pipelines/tmdb_metadata_pipeline.py
    deps:
      - pipelines/tmdb_metadata_pipeline.py
      - src/base_client.py
      - utils/downloader.py
      - services/tv_api.py
      - src/base_client.py
    outs:
      - data/raw/movies_metadata.json
      - data/raw/tv_metadata.json
      - app/static/images/movie
      - app/static/images/tv
      - app/static/images/cast

  extract_tmdb_features:
    cmd: python steps/extract_tmdb_features.py
    deps:
      - steps/extract_tmdb_features.py
      - data/raw/movies_metadata.json
      - data/raw/tv_metadata.json
    outs:
      - data/raw/movies_features.json
      - data/raw/tv_features.json
      - data/raw/movies_reviews.json
      - data/raw/tv_reviews.json
      - data/raw/movie_cast_metadata.json
      - data/raw/tv_cast_metadata.json

  ingest:
    wdir: .
    cmd: python pipelines/ingest_pipeline.py
    deps:
      - pipelines/ingest_pipeline.py
      - steps/ingest_data.py
      - src/ingest_strategy.py
      - data/raw/ml-100k/u.data
      - data/raw/ml-100k/u.item
      - data/raw/ml-100k/u.user
    params:
      - ingest.base_path
      - ingest.processed_dir
    outs:
      - data/processed

  process_ratings_movielens:
    cmd: python pipelines/ratings_pipeline_movielens.py
    deps:
      - pipelines/ratings_pipeline_movielens.py
      - steps/prepare_data.py
      - data/processed/ratings.csv
      - src/data_strategy.py
    params:
      - process_ratings_movielens.file_path
      - process_ratings_movielens.out_dir
      - process_ratings_movielens.timestamp_col
      - process_ratings_movielens.test_size
    outs:
      - feature_repo/data/ratings_movielens

  process_movies_movielens:
    cmd: python pipelines/movies_pipeline_movielens.py
    deps:
      - pipelines/movies_pipeline_movielens.py
      - steps/prepare_data.py
      - data/processed/movies.csv
      - src/data_strategy.py
    params:
      - process_movies_movielens.file_path
      - process_movies_movielens.date_col
      - process_movies_movielens.out_dir
      - process_movies_movielens.vectorize_col
      - process_movies_movielens.max_features
    outs:
      - feature_repo/data/movies_movielens

  process_users_movielens:
    cmd: python pipelines/users_pipeline_movielens.py
    deps:
      - pipelines/users_pipeline_movielens.py
      - steps/prepare_data.py
      - data/processed/users.csv
      - src/data_strategy.py
    params:
      - process_users_movielens.file_path
      - process_users_movielens.enc_cols
      - process_users_movielens.out_dir
    outs:
      - feature_repo/data/users_movielens

  user_item_matrix:
    cmd: python -c "from pipelines.training_pipeline import save_user_item_matrix; save_user_item_matrix()"
    deps:
      - pipelines/training_pipeline.py
      - steps/get_historical_features.py
      - src/model_dev.py
    outs:
      - model/user_item_matrix.pkl
  
  user_based_cf:
    cmd: python -c "from pipelines.training_pipeline import user_based_cf_pipeline; user_based_cf_pipeline()"
    deps:
      - pipelines/training_pipeline.py
      - steps/train_model.py
      - src/model_dev.py
      - steps/get_historical_features.py
      - model/user_item_matrix.pkl

  item_based_cf:
    cmd: python -c "from pipelines.training_pipeline import item_based_cf_pipeline; item_based_cf_pipeline()"
    deps:
      - pipelines/training_pipeline.py
      - steps/train_model.py
      - src/model_dev.py
      - steps/get_historical_features.py
      - model/user_item_matrix.pkl
  
  process_movies_tmdb:
    cmd: python pipelines/movies_pipeline_tmdb.py
    deps:
      - pipelines/movies_pipeline_tmdb.py
      - steps/prepare_data.py
      - src/data_strategy.py
    params:
      - process_movies_tmdb.file_path
      - process_movies_tmdb.drop_cols
      - process_tv_tmdb.keep_cols
      - process_movies_tmdb.vectorize_cols
      - process_movies_tmdb.output_cols
      - process_movies_tmdb.normalize_col
      - process_movies_tmdb.enc_cols
      - process_movies_tmdb.multi_lable_enc_cols
      - process_movies_tmdb.log_transform_cols
      - process_movies_tmdb.out_dir
    outs:
      - feature_repo/data/movies_tmdb

  process_tv_tmdb:
    cmd: python pipelines/tv_pipeline_tmdb.py
    deps:
      - pipelines/tv_pipeline_tmdb.py
      - steps/prepare_data.py
      - src/data_strategy.py
    params:
      - process_tv_tmdb.file_path
      - process_tv_tmdb.drop_cols
      - process_tv_tmdb.keep_cols
      - process_tv_tmdb.vectorize_cols
      - process_tv_tmdb.output_cols
      - process_tv_tmdb.normalize_col
      - process_tv_tmdb.enc_cols
      - process_tv_tmdb.multi_lable_enc_cols
      - process_tv_tmdb.log_transform_cols
      - process_tv_tmdb.out_dir
    outs:
      - feature_repo/data/tv_tmdb
      