stages:
  ingest:
    wdir: .
    cmd: python services/data_ingest_service/pipelines/ingest_pipeline.py
    deps:
      - services/data_ingest_service/pipelines/ingest_pipeline.py
      - services/data_ingest_service/steps/ingest_data.py
      - services/data_ingest_service/src/ingest_strategy.py
      - data/raw/ml-100k/u.data
      - data/raw/ml-100k/u.item
      - data/raw/ml-100k/u.user
    params:
      - services/data_ingest_service/params.yaml
    outs:
      - data/processed

  fetch_tmdb_metadata:
    cmd: python services/data_collection_service/pipelines/tmdb_metadata_pipeline.py
    deps:
      - services/data_collection_service/pipelines/tmdb_metadata_pipeline.py
      - services/data_collection_service/clients/tmdb_service_client.py
      - services/data_collection_service/utils/downloader.py
    outs:
      - data/raw/movies_metadata.json
      - data/raw/tv_metadata.json
      - services/web_service/static/images/movie
      - services/web_service/static/images/tv
      - services/web_service/static/images/cast
  
  extract_tmdb_features:
    cmd: python services/data_processing_service/steps/extract_tmdb_features.py
    deps:
      - python services/data_processing_service/steps/extract_tmdb_features.py
      - data/raw/movies_metadata.json
      - data/raw/tv_metadata.json
    outs:
      - data/raw/movies_features.json
      - data/raw/tv_features.json
      - data/raw/movies_reviews.json
      - data/raw/tv_reviews.json
      - data/raw/movie_cast_metadata.json
      - data/raw/tv_cast_metadata.json
      
  process_ratings_movielens:
    cmd: python services/data_processing_service/pipelines/ratings_pipeline_movielens.py
    deps:
      - services/data_processing_service/pipelines/ratings_pipeline_movielens.py
      - services/data_processing_service/steps/prepare_data.py
      - data/processed/ratings.csv
      - services/data_processing_service/src/data_strategy.py
    params:
      - services/data_processing_service/params.yaml
    outs:
      - data/feature/ratings_movielens

  process_movies_movielens:
    cmd: python services/data_processing_service/pipelines/movies_pipeline_movielens.py
    deps:
      - services/data_processing_service/pipelines/movies_pipeline_movielens.py
      - services/data_processing_service/steps/prepare_data.py
      - data/processed/movies.csv
      - services/data_processing_service/src/data_strategy.py
    params:
      - services/data_processing_service/params.yaml
    outs:
      - data/feature/movies_movielens

  process_users_movielens:
    cmd: python services/data_processing_service/pipelines/users_pipeline_movielens.py
    deps:
      - services/data_processing_service/pipelines/users_pipeline_movielens.py
      - services/data_processing_service/steps/prepare_data.py
      - services/data_processing_service/data/processed/users.csv
      - services/data_processing_service/src/data_strategy.py
    params:
      - services/data_processing_service/params.yaml
    outs:
      - data/feature/users_movielens

  process_movies_tmdb:
    cmd: python services/data_processing_service/pipelines/movies_pipeline_tmdb.py
    deps:
      - services/data_processing_service/pipelines/movies_pipeline_tmdb.py
      - services/data_processing_service/steps/prepare_data.py
      - services/data_processing_service/src/data_strategy.py
    params:
      - services/data_processing_service/params.yaml
    outs:
      - data/feature/movies_tmdb

  process_tv_tmdb:
    cmd: python services/data_processing_service/pipelines/tv_pipeline_tmdb.py
    deps:
      - services/data_processing_service/pipelines/tv_pipeline_tmdb.py
      - services/data_processing_service/steps/prepare_data.py
      - services/data_processing_service/src/data_strategy.py
    params:
      - services/data_processing_service/params.yaml
    outs:
      - data/feature/tv_tmdb
      
  user_item_matrix:
      cmd: python -c "from services.train_service.pipelines.training_pipeline import save_user_item_matrix; save_user_item_matrix()"
      deps:
        - services/train_service/pipelines/training_pipeline.py
        - services/data_processing_service/steps/get_historical_features.py
        - src/model_dev.py
      outs:
        - model/user_item_matrix.pkl
    
  user_based_cf:
      cmd: python -c "from services.train_service.pipelines.training_pipeline import user_based_cf_pipeline; user_based_cf_pipeline()"
      deps:
        - services/train_service/pipelines/training_pipeline.py
        - services/train_service/steps/train_model.py
        - services/train_service/src/model_dev.py
        - services/train_service/steps/get_historical_features.py
        - model/user_item_matrix.pkl

  item_based_cf:
      cmd: python -c "from services.train_service.pipelines.training_pipeline import item_based_cf_pipeline; item_based_cf_pipeline()"
      deps:
        - services/train_service/pipelines/training_pipeline.py
        - services/train_service/steps/train_model.py
        - services/train_service/src/model_dev.py
        - services/train_service/steps/get_historical_features.py
        - model/user_item_matrix.pkl