stages:
  ingest:
    wdir: .
    cmd: python pipelines/ingest_pipeline.py
    deps:
      - pipelines/ingest_pipeline.py
      - steps/ingest_data.py
      - src/ingest_strategy.py
      - data/raw/ml-100k/u.data
      - data/raw/ml-100k/u.item
      - data/raw/ml-100k/u.user
    params:
      - ingest.base_path
      - ingest.processed_dir
    outs:
      - data/processed

  process_ratings:
    cmd: python pipelines/ratings_pipeline.py
    deps:
      - pipelines/ratings_pipeline.py
      - steps/prepare_data.py
      - data/processed/ratings.csv
    params:
      - process_ratings.file_path
      - process_ratings.out_dir
      - process_ratings.timestamp_col
      - process_ratings.test_size
    outs:
      - feature_repo/data/ratings

  process_movies:
    cmd: python pipelines/movies_pipeline.py
    deps:
      - pipelines/movies_pipeline.py
      - steps/prepare_data.py
      - data/processed/movies.csv
    params:
      - process_movies.file_path
      - process_movies.date_col
      - process_movies.out_dir
      - process_movies.vectorize_col
      - process_movies.max_features
    outs:
      - feature_repo/data/movies

  process_users:
    cmd: python pipelines/users_pipeline.py
    deps:
      - pipelines/users_pipeline.py
      - steps/prepare_data.py
      - data/processed/users.csv
    params:
      - process_users.file_path
      - process_users.enc_cols
      - process_users.out_dir
    outs:
      - feature_repo/data/users

  user_item_matrix:
    cmd: python -c "from pipelines.training_pipeline import save_user_item_matrix; save_user_item_matrix()"
    deps:
      - pipelines/training_pipeline.py
      - steps/fetch_features.py
      - src/model_dev.py
    outs:
      - model/user_item_matrix.pkl
  
  user_based_cf:
    cmd: python -c "from pipelines.training_pipeline import user_based_cf_pipeline; user_based_cf_pipeline()"
    deps:
      - pipelines/training_pipeline.py
      - steps/train_model.py
      - src/model_dev.py
      - steps/fetch_features.py
      - model/user_item_matrix.pkl
    outs:
      - model/user_based_cf_model.pkl

  item_based_cf:
    cmd: python -c "from pipelines.training_pipeline import item_based_cf_pipeline; item_based_cf_pipeline()"
    deps:
      - pipelines/training_pipeline.py
      - steps/train_model.py
      - src/model_dev.py
      - steps/fetch_features.py
      - model/user_item_matrix.pkl
    outs:
      - model/item_based_cf_model.pkl
  