apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-store-service
  labels:
    app: feature_store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature_store
  template:
    metadata:
      labels:
        app: feature_store
    spec:
      containers:
      - name: feature-store-container
        image: ghcr.io/minhtb105/feature_store_service:${github.sha}
        ports:
        - containerPort: 8002
  