apiVersion: v1
kind: Service
metadata:
  name: data-collection-service
spec:
  selector:
    app: data-collection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: LoadBalancer
