stages: 
  user_item_matrix:
      cmd: python -c "from pipelines.training_pipeline import save_user_item_matrix; save_user_item_matrix()"
      deps:
        - pipelines/training_pipeline.py
        - steps/get_historical_features.py
        - src/model_dev.py
      outs:
        - model/user_item_matrix.pkl
    
    user_based_cf:
      cmd: python -c "from pipelines.training_pipeline import user_based_cf_pipeline; user_based_cf_pipeline()"
      deps:
        - pipelines/training_pipeline.py
        - steps/train_model.py
        - src/model_dev.py
        - steps/get_historical_features.py
        - model/user_item_matrix.pkl

    item_based_cf:
      cmd: python -c "from pipelines.training_pipeline import item_based_cf_pipeline; item_based_cf_pipeline()"
      deps:
        - pipelines/training_pipeline.py
        - steps/train_model.py
        - src/model_dev.py
        - steps/get_historical_features.py
        - model/user_item_matrix.pkl