stages:
  fetch_tmdb_metadata:
    cmd: python pipelines/tmdb_metadata_pipeline.py
    deps:
      - pipelines/tmdb_metadata_pipeline.py
      - src/base_client.py
      - utils/downloader.py
      - services/tv_api.py
      - src/base_client.py
    outs:
      - data/raw/movies_metadata.json
      - data/raw/tv_metadata.json
      - app/static/images/movie
      - app/static/images/tv
      - app/static/images/cast